### ISSUE TITLE
Method autowiring does not work with Spring Boot 2.1.10.RELEASE

### ISSUE THREAD

**Issue by imavroukakis** [jqwik-team/jqwik-spring#6]
Unfortunately, method autowiring fails on Spring Boot 2.1.10.RELEASE with the following error

```
java.lang.NoClassDefFoundError: org/springframework/beans/factory/annotation/ParameterResolutionDelegate

	at net.jqwik.spring.ResolveSpringParametersHook.canParameterBeResolved(ResolveSpringParametersHook.java:31)
	at net.jqwik.spring.ResolveSpringParametersHook.resolve(ResolveSpringParametersHook.java:22)
	at net.jqwik.engine.execution.lifecycle.CombinedResolveParameterHook.lambda$resolve$0(CombinedResolveParameterHook.java:23)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.execution.lifecycle.CombinedResolveParameterHook.resolve(CombinedResolveParameterHook.java:25)
	at net.jqwik.engine.execution.ParameterSupplierResolver.computeSupplier(ParameterSupplierResolver.java:37)
	at net.jqwik.engine.execution.ParameterSupplierResolver.lambda$resolveParameter$0(ParameterSupplierResolver.java:32)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at net.jqwik.engine.execution.ParameterSupplierResolver.resolveParameter(ParameterSupplierResolver.java:32)
	at net.jqwik.engine.execution.ParameterSupplierResolver.resolveParameter(ParameterSupplierResolver.java:25)
	at net.jqwik.engine.execution.DefaultPropertyLifecycleContext.resolveParameter(DefaultPropertyLifecycleContext.java:74)
	at net.jqwik.engine.hooks.lifecycle.MethodParameterResolver.resolveParameters(MethodParameterResolver.java:21)
	at net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.callPropertyMethods(PropertyLifecycleMethodsHook.java:23)
	at net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.beforeProperty(PropertyLifecycleMethodsHook.java:16)
	at 
[..snipped..]
```

Any chance of adding support for 2.1.x ?

Thanks!

**Comment by jlink** [comment]
Just checked. The testing support in Spring changed dramatically with versions >= 5.2.0. Spring Boot 2.1.10 works with Spring 5.1.11 :-(

Support versions < 5.2.0 would require both
- A significant duplication of what Spring test support does starting 5.2.0
- An additional artefact

Unless someone in the community is willing to invest that time it's not happening on my side.

**Comment by jlink** [comment]
@imavroukakis Assuming this is no longer an important thing. Feel free to re-open if it is.
